using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Aktivitetsrapport
{
    /// <summary>
    /// Interaction logic for Window1.xaml
    /// </summary>
    public partial class Settings : Window
    {
        private class setlist
        {

            public string Name { get; set; }
            public string Value { get; set; }

        }

        List<setlist> listan;

        public Settings()
        {
            InitializeComponent();

            WindowStartupLocation = WindowStartupLocation.CenterOwner;
            Owner = Application.Current.MainWindow;

            listan = new List<setlist>();

            foreach (System.Configuration.SettingsProperty prop in Properties.Settings.Default.Properties)
            {

                setlist l = new setlist();
                l.Name = prop.Name;
                l.Value = Properties.Settings.Default[prop.Name].ToString();

                listan.Add(l);

            }

            datagrid_settings.AutoGenerateColumns = true;
            datagrid_settings.ItemsSource = listan;

           

        }



        private void btn_cancel_Click(object sender, RoutedEventArgs e)
        {
            this.Close();
        }

        private void btn_ok_Click(object sender, RoutedEventArgs e)
        {

            foreach (System.Configuration.SettingsProperty prop in Properties.Settings.Default.Properties)
            {
                foreach (setlist l in listan)
                {

                    if (prop.Name == l.Name)
                        Properties.Settings.Default[prop.Name] = l.Value;

                }
            }

            this.DialogResult = true;
            this.Close();
        }

        private void datagrid_settings_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var column in datagrid_settings.Columns)
            {
                column.Width = new DataGridLength(1, DataGridLengthUnitType.Star);

            }

            datagrid_settings.Columns[0].IsReadOnly = true;

            datagrid_settings.Items.SortDescriptions.Add(new SortDescription("Name", ListSortDirection.Ascending));

        }

    }
}
